title: GRiD 
author: UMass Amherst GRiD group
description: Website of the "Graduate Researchers interested in Data" group. 

markdown: kramdown
permalink: /:title

url: "gridclub.io" 
baseurl: 

highlighter: rouge

sass:
  sass_dir: public/css
  style: :compressed

collections:
  events:
    output: true
    permalink: /events/:path/