title: GRiD 
author: UMass Amherst GRiD group
description: Website of the "Graduate Researchers interested in Data" group. 

markdown: kramdown
highlighter: null
permalink: /:title

url:
baseurl:


sass:
  sass_dir: public/css
  style: :compressed
